"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SIPrefix = exports.MarkerType = exports.MarkerStatus = exports.Access = void 0;
var accessgrant_pb_1 = require("../proto/provenance/marker/v1/accessgrant_pb");
Object.defineProperty(exports, "Access", { enumerable: true, get: function () { return accessgrant_pb_1.Access; } });
var marker_pb_1 = require("../proto/provenance/marker/v1/marker_pb");
Object.defineProperty(exports, "MarkerStatus", { enumerable: true, get: function () { return marker_pb_1.MarkerStatus; } });
Object.defineProperty(exports, "MarkerType", { enumerable: true, get: function () { return marker_pb_1.MarkerType; } });
var si_pb_1 = require("../proto/provenance/marker/v1/si_pb");
Object.defineProperty(exports, "SIPrefix", { enumerable: true, get: function () { return si_pb_1.SIPrefix; } });
