// source: provenance/metadata/v1/specification.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var gogoproto_gogo_pb = require('../../../gogoproto/gogo_pb.js');
goog.object.extend(proto, gogoproto_gogo_pb);
goog.exportSymbol('proto.provenance.metadata.v1.ContractSpecification', null, global);
goog.exportSymbol('proto.provenance.metadata.v1.ContractSpecification.SourceCase', null, global);
goog.exportSymbol('proto.provenance.metadata.v1.DefinitionType', null, global);
goog.exportSymbol('proto.provenance.metadata.v1.Description', null, global);
goog.exportSymbol('proto.provenance.metadata.v1.InputSpecification', null, global);
goog.exportSymbol('proto.provenance.metadata.v1.InputSpecification.SourceCase', null, global);
goog.exportSymbol('proto.provenance.metadata.v1.PartyType', null, global);
goog.exportSymbol('proto.provenance.metadata.v1.RecordSpecification', null, global);
goog.exportSymbol('proto.provenance.metadata.v1.ScopeSpecification', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.provenance.metadata.v1.ScopeSpecification = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.provenance.metadata.v1.ScopeSpecification.repeatedFields_, null);
};
goog.inherits(proto.provenance.metadata.v1.ScopeSpecification, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.provenance.metadata.v1.ScopeSpecification.displayName = 'proto.provenance.metadata.v1.ScopeSpecification';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.provenance.metadata.v1.ContractSpecification = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.provenance.metadata.v1.ContractSpecification.repeatedFields_, proto.provenance.metadata.v1.ContractSpecification.oneofGroups_);
};
goog.inherits(proto.provenance.metadata.v1.ContractSpecification, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.provenance.metadata.v1.ContractSpecification.displayName = 'proto.provenance.metadata.v1.ContractSpecification';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.provenance.metadata.v1.RecordSpecification = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.provenance.metadata.v1.RecordSpecification.repeatedFields_, null);
};
goog.inherits(proto.provenance.metadata.v1.RecordSpecification, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.provenance.metadata.v1.RecordSpecification.displayName = 'proto.provenance.metadata.v1.RecordSpecification';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.provenance.metadata.v1.InputSpecification = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.provenance.metadata.v1.InputSpecification.oneofGroups_);
};
goog.inherits(proto.provenance.metadata.v1.InputSpecification, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.provenance.metadata.v1.InputSpecification.displayName = 'proto.provenance.metadata.v1.InputSpecification';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.provenance.metadata.v1.Description = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.provenance.metadata.v1.Description, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.provenance.metadata.v1.Description.displayName = 'proto.provenance.metadata.v1.Description';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.provenance.metadata.v1.ScopeSpecification.repeatedFields_ = [3,4,5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.provenance.metadata.v1.ScopeSpecification.prototype.toObject = function(opt_includeInstance) {
  return proto.provenance.metadata.v1.ScopeSpecification.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.provenance.metadata.v1.ScopeSpecification} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.provenance.metadata.v1.ScopeSpecification.toObject = function(includeInstance, msg) {
  var f, obj = {
    specificationId: msg.getSpecificationId_asB64(),
    description: (f = msg.getDescription()) && proto.provenance.metadata.v1.Description.toObject(includeInstance, f),
    ownerAddressesList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
    partiesInvolvedList: (f = jspb.Message.getRepeatedField(msg, 4)) == null ? undefined : f,
    contractSpecIdsList: msg.getContractSpecIdsList_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.provenance.metadata.v1.ScopeSpecification}
 */
proto.provenance.metadata.v1.ScopeSpecification.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.provenance.metadata.v1.ScopeSpecification;
  return proto.provenance.metadata.v1.ScopeSpecification.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.provenance.metadata.v1.ScopeSpecification} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.provenance.metadata.v1.ScopeSpecification}
 */
proto.provenance.metadata.v1.ScopeSpecification.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setSpecificationId(value);
      break;
    case 2:
      var value = new proto.provenance.metadata.v1.Description;
      reader.readMessage(value,proto.provenance.metadata.v1.Description.deserializeBinaryFromReader);
      msg.setDescription(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addOwnerAddresses(value);
      break;
    case 4:
      var values = /** @type {!Array<!proto.provenance.metadata.v1.PartyType>} */ (reader.isDelimited() ? reader.readPackedEnum() : [reader.readEnum()]);
      for (var i = 0; i < values.length; i++) {
        msg.addPartiesInvolved(values[i]);
      }
      break;
    case 5:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.addContractSpecIds(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.provenance.metadata.v1.ScopeSpecification.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.provenance.metadata.v1.ScopeSpecification.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.provenance.metadata.v1.ScopeSpecification} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.provenance.metadata.v1.ScopeSpecification.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSpecificationId_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getDescription();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.provenance.metadata.v1.Description.serializeBinaryToWriter
    );
  }
  f = message.getOwnerAddressesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
  f = message.getPartiesInvolvedList();
  if (f.length > 0) {
    writer.writePackedEnum(
      4,
      f
    );
  }
  f = message.getContractSpecIdsList_asU8();
  if (f.length > 0) {
    writer.writeRepeatedBytes(
      5,
      f
    );
  }
};


/**
 * optional bytes specification_id = 1;
 * @return {!(string|Uint8Array)}
 */
proto.provenance.metadata.v1.ScopeSpecification.prototype.getSpecificationId = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes specification_id = 1;
 * This is a type-conversion wrapper around `getSpecificationId()`
 * @return {string}
 */
proto.provenance.metadata.v1.ScopeSpecification.prototype.getSpecificationId_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getSpecificationId()));
};


/**
 * optional bytes specification_id = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getSpecificationId()`
 * @return {!Uint8Array}
 */
proto.provenance.metadata.v1.ScopeSpecification.prototype.getSpecificationId_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getSpecificationId()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.provenance.metadata.v1.ScopeSpecification} returns this
 */
proto.provenance.metadata.v1.ScopeSpecification.prototype.setSpecificationId = function(value) {
  return jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * optional Description description = 2;
 * @return {?proto.provenance.metadata.v1.Description}
 */
proto.provenance.metadata.v1.ScopeSpecification.prototype.getDescription = function() {
  return /** @type{?proto.provenance.metadata.v1.Description} */ (
    jspb.Message.getWrapperField(this, proto.provenance.metadata.v1.Description, 2));
};


/**
 * @param {?proto.provenance.metadata.v1.Description|undefined} value
 * @return {!proto.provenance.metadata.v1.ScopeSpecification} returns this
*/
proto.provenance.metadata.v1.ScopeSpecification.prototype.setDescription = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.provenance.metadata.v1.ScopeSpecification} returns this
 */
proto.provenance.metadata.v1.ScopeSpecification.prototype.clearDescription = function() {
  return this.setDescription(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.provenance.metadata.v1.ScopeSpecification.prototype.hasDescription = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated string owner_addresses = 3;
 * @return {!Array<string>}
 */
proto.provenance.metadata.v1.ScopeSpecification.prototype.getOwnerAddressesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.provenance.metadata.v1.ScopeSpecification} returns this
 */
proto.provenance.metadata.v1.ScopeSpecification.prototype.setOwnerAddressesList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.provenance.metadata.v1.ScopeSpecification} returns this
 */
proto.provenance.metadata.v1.ScopeSpecification.prototype.addOwnerAddresses = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.provenance.metadata.v1.ScopeSpecification} returns this
 */
proto.provenance.metadata.v1.ScopeSpecification.prototype.clearOwnerAddressesList = function() {
  return this.setOwnerAddressesList([]);
};


/**
 * repeated PartyType parties_involved = 4;
 * @return {!Array<!proto.provenance.metadata.v1.PartyType>}
 */
proto.provenance.metadata.v1.ScopeSpecification.prototype.getPartiesInvolvedList = function() {
  return /** @type {!Array<!proto.provenance.metadata.v1.PartyType>} */ (jspb.Message.getRepeatedField(this, 4));
};


/**
 * @param {!Array<!proto.provenance.metadata.v1.PartyType>} value
 * @return {!proto.provenance.metadata.v1.ScopeSpecification} returns this
 */
proto.provenance.metadata.v1.ScopeSpecification.prototype.setPartiesInvolvedList = function(value) {
  return jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {!proto.provenance.metadata.v1.PartyType} value
 * @param {number=} opt_index
 * @return {!proto.provenance.metadata.v1.ScopeSpecification} returns this
 */
proto.provenance.metadata.v1.ScopeSpecification.prototype.addPartiesInvolved = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.provenance.metadata.v1.ScopeSpecification} returns this
 */
proto.provenance.metadata.v1.ScopeSpecification.prototype.clearPartiesInvolvedList = function() {
  return this.setPartiesInvolvedList([]);
};


/**
 * repeated bytes contract_spec_ids = 5;
 * @return {!(Array<!Uint8Array>|Array<string>)}
 */
proto.provenance.metadata.v1.ScopeSpecification.prototype.getContractSpecIdsList = function() {
  return /** @type {!(Array<!Uint8Array>|Array<string>)} */ (jspb.Message.getRepeatedField(this, 5));
};


/**
 * repeated bytes contract_spec_ids = 5;
 * This is a type-conversion wrapper around `getContractSpecIdsList()`
 * @return {!Array<string>}
 */
proto.provenance.metadata.v1.ScopeSpecification.prototype.getContractSpecIdsList_asB64 = function() {
  return /** @type {!Array<string>} */ (jspb.Message.bytesListAsB64(
      this.getContractSpecIdsList()));
};


/**
 * repeated bytes contract_spec_ids = 5;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getContractSpecIdsList()`
 * @return {!Array<!Uint8Array>}
 */
proto.provenance.metadata.v1.ScopeSpecification.prototype.getContractSpecIdsList_asU8 = function() {
  return /** @type {!Array<!Uint8Array>} */ (jspb.Message.bytesListAsU8(
      this.getContractSpecIdsList()));
};


/**
 * @param {!(Array<!Uint8Array>|Array<string>)} value
 * @return {!proto.provenance.metadata.v1.ScopeSpecification} returns this
 */
proto.provenance.metadata.v1.ScopeSpecification.prototype.setContractSpecIdsList = function(value) {
  return jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {!(string|Uint8Array)} value
 * @param {number=} opt_index
 * @return {!proto.provenance.metadata.v1.ScopeSpecification} returns this
 */
proto.provenance.metadata.v1.ScopeSpecification.prototype.addContractSpecIds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.provenance.metadata.v1.ScopeSpecification} returns this
 */
proto.provenance.metadata.v1.ScopeSpecification.prototype.clearContractSpecIdsList = function() {
  return this.setContractSpecIdsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.provenance.metadata.v1.ContractSpecification.repeatedFields_ = [3,4];

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.provenance.metadata.v1.ContractSpecification.oneofGroups_ = [[5,6]];

/**
 * @enum {number}
 */
proto.provenance.metadata.v1.ContractSpecification.SourceCase = {
  SOURCE_NOT_SET: 0,
  RESOURCE_ID: 5,
  HASH: 6
};

/**
 * @return {proto.provenance.metadata.v1.ContractSpecification.SourceCase}
 */
proto.provenance.metadata.v1.ContractSpecification.prototype.getSourceCase = function() {
  return /** @type {proto.provenance.metadata.v1.ContractSpecification.SourceCase} */(jspb.Message.computeOneofCase(this, proto.provenance.metadata.v1.ContractSpecification.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.provenance.metadata.v1.ContractSpecification.prototype.toObject = function(opt_includeInstance) {
  return proto.provenance.metadata.v1.ContractSpecification.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.provenance.metadata.v1.ContractSpecification} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.provenance.metadata.v1.ContractSpecification.toObject = function(includeInstance, msg) {
  var f, obj = {
    specificationId: msg.getSpecificationId_asB64(),
    description: (f = msg.getDescription()) && proto.provenance.metadata.v1.Description.toObject(includeInstance, f),
    ownerAddressesList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
    partiesInvolvedList: (f = jspb.Message.getRepeatedField(msg, 4)) == null ? undefined : f,
    resourceId: msg.getResourceId_asB64(),
    hash: jspb.Message.getFieldWithDefault(msg, 6, ""),
    className: jspb.Message.getFieldWithDefault(msg, 7, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.provenance.metadata.v1.ContractSpecification}
 */
proto.provenance.metadata.v1.ContractSpecification.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.provenance.metadata.v1.ContractSpecification;
  return proto.provenance.metadata.v1.ContractSpecification.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.provenance.metadata.v1.ContractSpecification} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.provenance.metadata.v1.ContractSpecification}
 */
proto.provenance.metadata.v1.ContractSpecification.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setSpecificationId(value);
      break;
    case 2:
      var value = new proto.provenance.metadata.v1.Description;
      reader.readMessage(value,proto.provenance.metadata.v1.Description.deserializeBinaryFromReader);
      msg.setDescription(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addOwnerAddresses(value);
      break;
    case 4:
      var values = /** @type {!Array<!proto.provenance.metadata.v1.PartyType>} */ (reader.isDelimited() ? reader.readPackedEnum() : [reader.readEnum()]);
      for (var i = 0; i < values.length; i++) {
        msg.addPartiesInvolved(values[i]);
      }
      break;
    case 5:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setResourceId(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setHash(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setClassName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.provenance.metadata.v1.ContractSpecification.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.provenance.metadata.v1.ContractSpecification.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.provenance.metadata.v1.ContractSpecification} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.provenance.metadata.v1.ContractSpecification.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSpecificationId_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getDescription();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.provenance.metadata.v1.Description.serializeBinaryToWriter
    );
  }
  f = message.getOwnerAddressesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
  f = message.getPartiesInvolvedList();
  if (f.length > 0) {
    writer.writePackedEnum(
      4,
      f
    );
  }
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeBytes(
      5,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getClassName();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
};


/**
 * optional bytes specification_id = 1;
 * @return {!(string|Uint8Array)}
 */
proto.provenance.metadata.v1.ContractSpecification.prototype.getSpecificationId = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes specification_id = 1;
 * This is a type-conversion wrapper around `getSpecificationId()`
 * @return {string}
 */
proto.provenance.metadata.v1.ContractSpecification.prototype.getSpecificationId_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getSpecificationId()));
};


/**
 * optional bytes specification_id = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getSpecificationId()`
 * @return {!Uint8Array}
 */
proto.provenance.metadata.v1.ContractSpecification.prototype.getSpecificationId_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getSpecificationId()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.provenance.metadata.v1.ContractSpecification} returns this
 */
proto.provenance.metadata.v1.ContractSpecification.prototype.setSpecificationId = function(value) {
  return jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * optional Description description = 2;
 * @return {?proto.provenance.metadata.v1.Description}
 */
proto.provenance.metadata.v1.ContractSpecification.prototype.getDescription = function() {
  return /** @type{?proto.provenance.metadata.v1.Description} */ (
    jspb.Message.getWrapperField(this, proto.provenance.metadata.v1.Description, 2));
};


/**
 * @param {?proto.provenance.metadata.v1.Description|undefined} value
 * @return {!proto.provenance.metadata.v1.ContractSpecification} returns this
*/
proto.provenance.metadata.v1.ContractSpecification.prototype.setDescription = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.provenance.metadata.v1.ContractSpecification} returns this
 */
proto.provenance.metadata.v1.ContractSpecification.prototype.clearDescription = function() {
  return this.setDescription(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.provenance.metadata.v1.ContractSpecification.prototype.hasDescription = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated string owner_addresses = 3;
 * @return {!Array<string>}
 */
proto.provenance.metadata.v1.ContractSpecification.prototype.getOwnerAddressesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.provenance.metadata.v1.ContractSpecification} returns this
 */
proto.provenance.metadata.v1.ContractSpecification.prototype.setOwnerAddressesList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.provenance.metadata.v1.ContractSpecification} returns this
 */
proto.provenance.metadata.v1.ContractSpecification.prototype.addOwnerAddresses = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.provenance.metadata.v1.ContractSpecification} returns this
 */
proto.provenance.metadata.v1.ContractSpecification.prototype.clearOwnerAddressesList = function() {
  return this.setOwnerAddressesList([]);
};


/**
 * repeated PartyType parties_involved = 4;
 * @return {!Array<!proto.provenance.metadata.v1.PartyType>}
 */
proto.provenance.metadata.v1.ContractSpecification.prototype.getPartiesInvolvedList = function() {
  return /** @type {!Array<!proto.provenance.metadata.v1.PartyType>} */ (jspb.Message.getRepeatedField(this, 4));
};


/**
 * @param {!Array<!proto.provenance.metadata.v1.PartyType>} value
 * @return {!proto.provenance.metadata.v1.ContractSpecification} returns this
 */
proto.provenance.metadata.v1.ContractSpecification.prototype.setPartiesInvolvedList = function(value) {
  return jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {!proto.provenance.metadata.v1.PartyType} value
 * @param {number=} opt_index
 * @return {!proto.provenance.metadata.v1.ContractSpecification} returns this
 */
proto.provenance.metadata.v1.ContractSpecification.prototype.addPartiesInvolved = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.provenance.metadata.v1.ContractSpecification} returns this
 */
proto.provenance.metadata.v1.ContractSpecification.prototype.clearPartiesInvolvedList = function() {
  return this.setPartiesInvolvedList([]);
};


/**
 * optional bytes resource_id = 5;
 * @return {!(string|Uint8Array)}
 */
proto.provenance.metadata.v1.ContractSpecification.prototype.getResourceId = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * optional bytes resource_id = 5;
 * This is a type-conversion wrapper around `getResourceId()`
 * @return {string}
 */
proto.provenance.metadata.v1.ContractSpecification.prototype.getResourceId_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getResourceId()));
};


/**
 * optional bytes resource_id = 5;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getResourceId()`
 * @return {!Uint8Array}
 */
proto.provenance.metadata.v1.ContractSpecification.prototype.getResourceId_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getResourceId()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.provenance.metadata.v1.ContractSpecification} returns this
 */
proto.provenance.metadata.v1.ContractSpecification.prototype.setResourceId = function(value) {
  return jspb.Message.setOneofField(this, 5, proto.provenance.metadata.v1.ContractSpecification.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.provenance.metadata.v1.ContractSpecification} returns this
 */
proto.provenance.metadata.v1.ContractSpecification.prototype.clearResourceId = function() {
  return jspb.Message.setOneofField(this, 5, proto.provenance.metadata.v1.ContractSpecification.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.provenance.metadata.v1.ContractSpecification.prototype.hasResourceId = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional string hash = 6;
 * @return {string}
 */
proto.provenance.metadata.v1.ContractSpecification.prototype.getHash = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.provenance.metadata.v1.ContractSpecification} returns this
 */
proto.provenance.metadata.v1.ContractSpecification.prototype.setHash = function(value) {
  return jspb.Message.setOneofField(this, 6, proto.provenance.metadata.v1.ContractSpecification.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.provenance.metadata.v1.ContractSpecification} returns this
 */
proto.provenance.metadata.v1.ContractSpecification.prototype.clearHash = function() {
  return jspb.Message.setOneofField(this, 6, proto.provenance.metadata.v1.ContractSpecification.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.provenance.metadata.v1.ContractSpecification.prototype.hasHash = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional string class_name = 7;
 * @return {string}
 */
proto.provenance.metadata.v1.ContractSpecification.prototype.getClassName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.provenance.metadata.v1.ContractSpecification} returns this
 */
proto.provenance.metadata.v1.ContractSpecification.prototype.setClassName = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.provenance.metadata.v1.RecordSpecification.repeatedFields_ = [3,6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.provenance.metadata.v1.RecordSpecification.prototype.toObject = function(opt_includeInstance) {
  return proto.provenance.metadata.v1.RecordSpecification.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.provenance.metadata.v1.RecordSpecification} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.provenance.metadata.v1.RecordSpecification.toObject = function(includeInstance, msg) {
  var f, obj = {
    specificationId: msg.getSpecificationId_asB64(),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    inputsList: jspb.Message.toObjectList(msg.getInputsList(),
    proto.provenance.metadata.v1.InputSpecification.toObject, includeInstance),
    typeName: jspb.Message.getFieldWithDefault(msg, 4, ""),
    resultType: jspb.Message.getFieldWithDefault(msg, 5, 0),
    responsiblePartiesList: (f = jspb.Message.getRepeatedField(msg, 6)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.provenance.metadata.v1.RecordSpecification}
 */
proto.provenance.metadata.v1.RecordSpecification.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.provenance.metadata.v1.RecordSpecification;
  return proto.provenance.metadata.v1.RecordSpecification.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.provenance.metadata.v1.RecordSpecification} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.provenance.metadata.v1.RecordSpecification}
 */
proto.provenance.metadata.v1.RecordSpecification.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setSpecificationId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = new proto.provenance.metadata.v1.InputSpecification;
      reader.readMessage(value,proto.provenance.metadata.v1.InputSpecification.deserializeBinaryFromReader);
      msg.addInputs(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setTypeName(value);
      break;
    case 5:
      var value = /** @type {!proto.provenance.metadata.v1.DefinitionType} */ (reader.readEnum());
      msg.setResultType(value);
      break;
    case 6:
      var values = /** @type {!Array<!proto.provenance.metadata.v1.PartyType>} */ (reader.isDelimited() ? reader.readPackedEnum() : [reader.readEnum()]);
      for (var i = 0; i < values.length; i++) {
        msg.addResponsibleParties(values[i]);
      }
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.provenance.metadata.v1.RecordSpecification.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.provenance.metadata.v1.RecordSpecification.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.provenance.metadata.v1.RecordSpecification} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.provenance.metadata.v1.RecordSpecification.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSpecificationId_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getInputsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.provenance.metadata.v1.InputSpecification.serializeBinaryToWriter
    );
  }
  f = message.getTypeName();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getResultType();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
  f = message.getResponsiblePartiesList();
  if (f.length > 0) {
    writer.writePackedEnum(
      6,
      f
    );
  }
};


/**
 * optional bytes specification_id = 1;
 * @return {!(string|Uint8Array)}
 */
proto.provenance.metadata.v1.RecordSpecification.prototype.getSpecificationId = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes specification_id = 1;
 * This is a type-conversion wrapper around `getSpecificationId()`
 * @return {string}
 */
proto.provenance.metadata.v1.RecordSpecification.prototype.getSpecificationId_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getSpecificationId()));
};


/**
 * optional bytes specification_id = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getSpecificationId()`
 * @return {!Uint8Array}
 */
proto.provenance.metadata.v1.RecordSpecification.prototype.getSpecificationId_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getSpecificationId()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.provenance.metadata.v1.RecordSpecification} returns this
 */
proto.provenance.metadata.v1.RecordSpecification.prototype.setSpecificationId = function(value) {
  return jspb.Message.setProto3BytesField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.provenance.metadata.v1.RecordSpecification.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.provenance.metadata.v1.RecordSpecification} returns this
 */
proto.provenance.metadata.v1.RecordSpecification.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated InputSpecification inputs = 3;
 * @return {!Array<!proto.provenance.metadata.v1.InputSpecification>}
 */
proto.provenance.metadata.v1.RecordSpecification.prototype.getInputsList = function() {
  return /** @type{!Array<!proto.provenance.metadata.v1.InputSpecification>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.provenance.metadata.v1.InputSpecification, 3));
};


/**
 * @param {!Array<!proto.provenance.metadata.v1.InputSpecification>} value
 * @return {!proto.provenance.metadata.v1.RecordSpecification} returns this
*/
proto.provenance.metadata.v1.RecordSpecification.prototype.setInputsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.provenance.metadata.v1.InputSpecification=} opt_value
 * @param {number=} opt_index
 * @return {!proto.provenance.metadata.v1.InputSpecification}
 */
proto.provenance.metadata.v1.RecordSpecification.prototype.addInputs = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.provenance.metadata.v1.InputSpecification, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.provenance.metadata.v1.RecordSpecification} returns this
 */
proto.provenance.metadata.v1.RecordSpecification.prototype.clearInputsList = function() {
  return this.setInputsList([]);
};


/**
 * optional string type_name = 4;
 * @return {string}
 */
proto.provenance.metadata.v1.RecordSpecification.prototype.getTypeName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.provenance.metadata.v1.RecordSpecification} returns this
 */
proto.provenance.metadata.v1.RecordSpecification.prototype.setTypeName = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional DefinitionType result_type = 5;
 * @return {!proto.provenance.metadata.v1.DefinitionType}
 */
proto.provenance.metadata.v1.RecordSpecification.prototype.getResultType = function() {
  return /** @type {!proto.provenance.metadata.v1.DefinitionType} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {!proto.provenance.metadata.v1.DefinitionType} value
 * @return {!proto.provenance.metadata.v1.RecordSpecification} returns this
 */
proto.provenance.metadata.v1.RecordSpecification.prototype.setResultType = function(value) {
  return jspb.Message.setProto3EnumField(this, 5, value);
};


/**
 * repeated PartyType responsible_parties = 6;
 * @return {!Array<!proto.provenance.metadata.v1.PartyType>}
 */
proto.provenance.metadata.v1.RecordSpecification.prototype.getResponsiblePartiesList = function() {
  return /** @type {!Array<!proto.provenance.metadata.v1.PartyType>} */ (jspb.Message.getRepeatedField(this, 6));
};


/**
 * @param {!Array<!proto.provenance.metadata.v1.PartyType>} value
 * @return {!proto.provenance.metadata.v1.RecordSpecification} returns this
 */
proto.provenance.metadata.v1.RecordSpecification.prototype.setResponsiblePartiesList = function(value) {
  return jspb.Message.setField(this, 6, value || []);
};


/**
 * @param {!proto.provenance.metadata.v1.PartyType} value
 * @param {number=} opt_index
 * @return {!proto.provenance.metadata.v1.RecordSpecification} returns this
 */
proto.provenance.metadata.v1.RecordSpecification.prototype.addResponsibleParties = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 6, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.provenance.metadata.v1.RecordSpecification} returns this
 */
proto.provenance.metadata.v1.RecordSpecification.prototype.clearResponsiblePartiesList = function() {
  return this.setResponsiblePartiesList([]);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.provenance.metadata.v1.InputSpecification.oneofGroups_ = [[3,4]];

/**
 * @enum {number}
 */
proto.provenance.metadata.v1.InputSpecification.SourceCase = {
  SOURCE_NOT_SET: 0,
  RECORD_ID: 3,
  HASH: 4
};

/**
 * @return {proto.provenance.metadata.v1.InputSpecification.SourceCase}
 */
proto.provenance.metadata.v1.InputSpecification.prototype.getSourceCase = function() {
  return /** @type {proto.provenance.metadata.v1.InputSpecification.SourceCase} */(jspb.Message.computeOneofCase(this, proto.provenance.metadata.v1.InputSpecification.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.provenance.metadata.v1.InputSpecification.prototype.toObject = function(opt_includeInstance) {
  return proto.provenance.metadata.v1.InputSpecification.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.provenance.metadata.v1.InputSpecification} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.provenance.metadata.v1.InputSpecification.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    typeName: jspb.Message.getFieldWithDefault(msg, 2, ""),
    recordId: msg.getRecordId_asB64(),
    hash: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.provenance.metadata.v1.InputSpecification}
 */
proto.provenance.metadata.v1.InputSpecification.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.provenance.metadata.v1.InputSpecification;
  return proto.provenance.metadata.v1.InputSpecification.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.provenance.metadata.v1.InputSpecification} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.provenance.metadata.v1.InputSpecification}
 */
proto.provenance.metadata.v1.InputSpecification.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTypeName(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setRecordId(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setHash(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.provenance.metadata.v1.InputSpecification.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.provenance.metadata.v1.InputSpecification.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.provenance.metadata.v1.InputSpecification} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.provenance.metadata.v1.InputSpecification.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTypeName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeBytes(
      3,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.provenance.metadata.v1.InputSpecification.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.provenance.metadata.v1.InputSpecification} returns this
 */
proto.provenance.metadata.v1.InputSpecification.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string type_name = 2;
 * @return {string}
 */
proto.provenance.metadata.v1.InputSpecification.prototype.getTypeName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.provenance.metadata.v1.InputSpecification} returns this
 */
proto.provenance.metadata.v1.InputSpecification.prototype.setTypeName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional bytes record_id = 3;
 * @return {!(string|Uint8Array)}
 */
proto.provenance.metadata.v1.InputSpecification.prototype.getRecordId = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes record_id = 3;
 * This is a type-conversion wrapper around `getRecordId()`
 * @return {string}
 */
proto.provenance.metadata.v1.InputSpecification.prototype.getRecordId_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getRecordId()));
};


/**
 * optional bytes record_id = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getRecordId()`
 * @return {!Uint8Array}
 */
proto.provenance.metadata.v1.InputSpecification.prototype.getRecordId_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getRecordId()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.provenance.metadata.v1.InputSpecification} returns this
 */
proto.provenance.metadata.v1.InputSpecification.prototype.setRecordId = function(value) {
  return jspb.Message.setOneofField(this, 3, proto.provenance.metadata.v1.InputSpecification.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.provenance.metadata.v1.InputSpecification} returns this
 */
proto.provenance.metadata.v1.InputSpecification.prototype.clearRecordId = function() {
  return jspb.Message.setOneofField(this, 3, proto.provenance.metadata.v1.InputSpecification.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.provenance.metadata.v1.InputSpecification.prototype.hasRecordId = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string hash = 4;
 * @return {string}
 */
proto.provenance.metadata.v1.InputSpecification.prototype.getHash = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.provenance.metadata.v1.InputSpecification} returns this
 */
proto.provenance.metadata.v1.InputSpecification.prototype.setHash = function(value) {
  return jspb.Message.setOneofField(this, 4, proto.provenance.metadata.v1.InputSpecification.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.provenance.metadata.v1.InputSpecification} returns this
 */
proto.provenance.metadata.v1.InputSpecification.prototype.clearHash = function() {
  return jspb.Message.setOneofField(this, 4, proto.provenance.metadata.v1.InputSpecification.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.provenance.metadata.v1.InputSpecification.prototype.hasHash = function() {
  return jspb.Message.getField(this, 4) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.provenance.metadata.v1.Description.prototype.toObject = function(opt_includeInstance) {
  return proto.provenance.metadata.v1.Description.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.provenance.metadata.v1.Description} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.provenance.metadata.v1.Description.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    description: jspb.Message.getFieldWithDefault(msg, 3, ""),
    websiteUrl: jspb.Message.getFieldWithDefault(msg, 4, ""),
    iconUrl: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.provenance.metadata.v1.Description}
 */
proto.provenance.metadata.v1.Description.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.provenance.metadata.v1.Description;
  return proto.provenance.metadata.v1.Description.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.provenance.metadata.v1.Description} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.provenance.metadata.v1.Description}
 */
proto.provenance.metadata.v1.Description.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setWebsiteUrl(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setIconUrl(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.provenance.metadata.v1.Description.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.provenance.metadata.v1.Description.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.provenance.metadata.v1.Description} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.provenance.metadata.v1.Description.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getWebsiteUrl();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getIconUrl();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.provenance.metadata.v1.Description.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.provenance.metadata.v1.Description} returns this
 */
proto.provenance.metadata.v1.Description.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string description = 3;
 * @return {string}
 */
proto.provenance.metadata.v1.Description.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.provenance.metadata.v1.Description} returns this
 */
proto.provenance.metadata.v1.Description.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string website_url = 4;
 * @return {string}
 */
proto.provenance.metadata.v1.Description.prototype.getWebsiteUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.provenance.metadata.v1.Description} returns this
 */
proto.provenance.metadata.v1.Description.prototype.setWebsiteUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string icon_url = 5;
 * @return {string}
 */
proto.provenance.metadata.v1.Description.prototype.getIconUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.provenance.metadata.v1.Description} returns this
 */
proto.provenance.metadata.v1.Description.prototype.setIconUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * @enum {number}
 */
proto.provenance.metadata.v1.DefinitionType = {
  DEFINITION_TYPE_UNSPECIFIED: 0,
  DEFINITION_TYPE_PROPOSED: 1,
  DEFINITION_TYPE_RECORD: 2,
  DEFINITION_TYPE_RECORD_LIST: 3
};

/**
 * @enum {number}
 */
proto.provenance.metadata.v1.PartyType = {
  PARTY_TYPE_UNSPECIFIED: 0,
  PARTY_TYPE_ORIGINATOR: 1,
  PARTY_TYPE_SERVICER: 2,
  PARTY_TYPE_INVESTOR: 3,
  PARTY_TYPE_CUSTODIAN: 4,
  PARTY_TYPE_OWNER: 5,
  PARTY_TYPE_AFFILIATE: 6,
  PARTY_TYPE_OMNIBUS: 7,
  PARTY_TYPE_PROVENANCE: 8,
  PARTY_TYPE_CONTROLLER: 10,
  PARTY_TYPE_VALIDATOR: 11
};

goog.object.extend(exports, proto.provenance.metadata.v1);
